default:
  name: torrent-web-seeder
  endpointsProvider: Environment
vod:
  name: nginx-vod
  endpointsProvider: Environment
arch:
  name: torrent-archiver
  endpointsProvider: Environment
hls:
  name: content-transcoder
  endpointsProvider: Environment
vtt:
  name: srt2vtt
  endpointsProvider: Environment
ext:
  name: external-proxy
  endpointsProvider: Environment