#!/command/with-contenv sh

log() {
   echo "$1" | s6-log p"[create-s3-buckets]" 1
}

set -a
source /etc/webtor/common.env
set +a

log "provisioning S3 buckets under ${STORAGE_DIR}"
for b in vault posters subtitles thumbnails; do
  mkdir -p "$STORAGE_DIR/$b"
done
