#!/command/with-contenv sh

log() {
   echo "$1" | s6-log p"[generate-s3-credentials]" 1
}

f=/etc/webtor/secrets/s3.env
mkdir -p "$(dirname "$f")"
if [ -n "$AWS_ACCESS_KEY_ID" ] && [ -n "$AWS_SECRET_ACCESS_KEY" ]; then
  log "using provided AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY"
  key=$AWS_ACCESS_KEY_ID
  secret=$AWS_SECRET_ACCESS_KEY
elif [ -f $f ]; then
  log "credentials file ${f} already exists"
  exit
else
  log "generating S3 credentials"
  key=$(uuidgen | tr -d '-' | head -c 20)
  secret=$(uuidgen | sha1sum | head -c 40)
fi
log "storing S3 credentials to ${f}"
umask 077
echo "AWS_ACCESS_KEY_ID=${key}" > $f
echo "AWS_SECRET_ACCESS_KEY=${secret}" >> $f
chmod 600 $f
